[tool:pytest]
DJANGO_SETTINGS_MODULE = config.settings
addopts = --html=reports/test_report.html --self-contained-html
python_files = tests.py
testpaths = accounts campaigns pledges payments moderation notifications_app frontend